gd:
	#rm -f gradient_descent && g++ steep_gradient_descent.cpp  common.cpp linear_search.cpp  read_problem.cpp  vec_op.cpp -o gradient_descent
	rm -f gradient_descent && g++ steep_gradient_descent.cpp  common.cpp linear_search.cpp  read_problem.cpp  vec_op.cpp -o gradient_descent

